[package]
name = "rust-base-skeleton"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
fake = "2.4"
rand = "0.8"
